# Generated by Django 3.2 on 2024-04-28 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='imagem',
            new_name='imagen',
        ),
    ]
